# Generated by Django 4.2.14 on 2025-01-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0002_center_created_at_center_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('id_type', models.CharField(choices=[('civil_registry', 'Civil Registry'), ('resident_id', 'Resident ID'), ('violator_refugee_id', 'Violator Refugee ID'), ('replacement_card', 'Replacement Card')], max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(max_length=100)),
                ('case_number', models.CharField(max_length=100)),
                ('arresting_authority', models.CharField(max_length=100)),
                ('arresting_place', models.CharField(max_length=100)),
                ('arresting_date', models.DateField()),
                ('detention_agency', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('under_investigation', 'Under Investigation'), ('in_court', 'In Court'), ('judgment_issued', 'Judgment Issued'), ('in_prison', 'In Prison'), ('released', 'Released')], default='under_investigation', max_length=100)),
                ('detainee_status', models.CharField(choices=[('detained', 'Detained (Under Investigation)'), ('under_review', 'Under Review (In Court)'), ('sentenced', 'Sentenced (Judgment Issued)'), ('imprisoned', 'Imprisoned (Transferred to Prison)'), ('released', 'Released (From Custody)')], default='detained', max_length=100)),
                ('judgment_date', models.DateField(blank=True, help_text='The date of the judgment.', null=True)),
                ('sentence_duration', models.DurationField(blank=True, help_text='The duration of the sentence.', null=True)),
                ('sentence_start_date', models.DateField(blank=True, help_text='The start date of the sentence.', null=True)),
                ('sentence_end_date', models.DateField(blank=True, help_text='The end date of the sentence.', null=True)),
                ('prison_arrival_date', models.DateField(blank=True, help_text='The date the detainee arrived at the prison.', null=True)),
                ('release_date', models.DateField(blank=True, help_text='The release date of the detainee.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='centers.center')),
                ('detainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.detainee')),
            ],
        ),
    ]
