# Generated by Django 4.2.14 on 2025-01-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='sentence_duration',
            field=models.CharField(blank=True, help_text='The duration of the sentence.', max_length=100, null=True),
        ),
    ]
