# Generated by Django 4.2.6 on 2025-01-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_sentence_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detainee',
            unique_together={('id_type', 'id_number')},
        ),
    ]
