# Generated by Django 4.2.6 on 2025-01-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_detainee_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detainee',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='detainee',
            constraint=models.UniqueConstraint(fields=('id_type', 'id_number'), name='unique_detainee_id'),
        ),
    ]
