# Generated by Django 4.2.14 on 2025-01-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('centers', '0002_center_created_at_center_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centeruser',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_user', to='centers.center'),
        ),
        migrations.AlterField(
            model_name='centeruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='center_user', to='users.regularuser'),
        ),
    ]
