# Generated by Django 4.2.14 on 2025-01-18 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('centers', '0003_alter_centeruser_center_alter_centeruser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centeruser',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='centers.center'),
        ),
        migrations.AlterField(
            model_name='centeruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='center', to='users.regularuser'),
        ),
    ]
